name: CI to Docker Registry

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Updated to the latest version

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: edgartest.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3 # Updated to the latest version
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: edgartest.azurecr.io/my-fastapi-app:latest
